ARG FISH_VERSION
ARG ALPINE_VERSION
FROM alpine:${ALPINE_VERSION}

# Redeclare ARG so its value is available after FROM (cf. https://github.com/moby/moby/issues/34129#issuecomment-417609075)
ARG FISH_VERSION
RUN printf "\nBuilding \e[38;5;27mFish-%s\e[m\n\n" ${FISH_VERSION}


# Common runtime dependencies of the fish shell
RUN apk add --no-cache \
    coreutils \
    curl \
    git \
    fish

ENTRYPOINT ["fish", "-c"]
CMD [ "fish" ]
